### ISSUE TITLE
i did some changes

### ISSUE THREAD

**Issue by evert-mouw** [allanlaal/weather-calendar-feed#4]
Great stuff :-)  Now I can import weather forecasts in Orage, calcurse and Outlook.
I've made a few changes to the index.php, please use diff/meld to see the changes.
Quick overview:
- using beaufort for wind speed, so requiring windspeed.php
- mv index.php get.php
- replaced and added a few weather emoji for the summary
- event availability is now "free" (don't show as busy)
- using the "Conditions" to determine precipitation_icon when temp_min>0
- choice between one weather icon (calculates averages) or multiple emoji using a URL param

Here you go: (**removed, see pull request**)

**Comment by allanlaal** [comment]
nice work :)

could you submit these as a pull request? it'll save me from manually merging these

**Comment by evert-mouw** [comment]
i'll do that later -- some of my code is a mess to be honest, i'll do some cleanup first

**Comment by BjornGrylls** [comment]
Hi
In evert-mouw's index.php on line 141 you need to add this line of code:
$conditions_all = explode('#', substr($conditions_wholeday, 0, -1));

I don't know where I should let you know so I'll just post it here.

**Comment by evert-mouw** [comment]
> Hi
> In evert-mouw's index.php on line 141 you need to add this line of code:
> $conditions_all = explode('#', substr($conditions_wholeday, 0, -1));
> 
> I don't know where I should let you know so I'll just post it here.

Forgive me my very late reply. I've added your suggestion. Thanks!

**Comment by allanlaal** [comment]
#5 has been merged, thank you @evert-mouw 
if anyone else wants their fork merged, do a PR too :)
